.base: &base
  hostname: siscop.com.br
  user: saapr376
  port: 2222
  identityFile: ~/.ssh/id_rsa
  forwardAgent: true
  multiplexing: true
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no

homologacao:
  <<: *base
  stage: homologacao
  deploy_path: ~/ambientes/homologacao

producao:
  <<: *base
  stage: producao
  deploy_path: ~/ambientes/producao

localhost:
  local: true
  stage: local
  deploy_path: ~/ambientes/local
  branch: develop
